[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_OPENAI_API_KEY = ""
  SPOTIFY_CLIENT_ID = ""
  SPOTIFY_CLIENT_SECRET = ""
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".env.local"]

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle Next.js static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[build.processing]
  skip_processing = false 